### ISSUE TITLE
bash script downloading only imaging 

### ISSUE THREAD

**Issue by loressa** [neheller/kits21#47]
Hello,

I might be doing something silly, but I used the bash option get_imaging.sh and it only downloads the imaging.nii.gz files. How do I get the labels (segmentations)? I tried installing but pip install always result in errors.

Thanks,
Lorena

**Comment by neheller** [comment]
Hello! The segmentations should be coming down with the repository when you clone it. Since there are multiple segmentations per instance, there are various ways in which they can be combined. The files you are probably looking for are `kits21/data/*/aggregated_MAJ_seg.nii.gz` which combine labels with majority voting.

**Comment by loressa** [comment]
oh, I see what's happened! When using the script as in the README.md, i.e.`bash kits21/starter_code/get_imaging.sh`, it meant it created another data directory in the current directory rather than adding the images in kits21/data. Thank you I got them now!
