### ISSUE TITLE
case_00205 Cyst Instance 1 and Tumor Instance 3 segment the same region 

### ISSUE THREAD

**Issue by mibaumgartner** [neheller/kits21#58]
Hi Nick, excellent work with KiTS21 :)

I noticed that Instance 1 Cyst and Instance 3 Tumor refer to the same structure in case 00205, is that intended?. Considering that there was no Tumor region in KiTS19 I guess it is supposed to be a cyst. 

Best,
Michael

**Comment by neheller** [comment]
That was not intended, and thank you for catching that! My feeling is you are correct but let me consult with our clinical team and get back to you.

**Comment by neheller** [comment]
In fact, this was a label error from KiTS19, and it is correct as a tumor. This is an angiomyolipoma case and that can cause tumors of very low radiodensity. It was originally erroneously labeled as a cyst but was later reclassified as a tumor. Unfortunately, due to a bug in our import script, the original cyst instance was not deleted, and that is why it appears twice.

I've merged in [a change](https://github.com/neheller/kits21/pull/59) which deletes these instances. Thanks again for the heads up!

**Comment by mibaumgartner** [comment]
Awesome, I'll update my local version :) Thanks for the super quick update!
